//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://bird.kartaca.com/xmlschema/admin/delivery}DeliveryItem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="body" type="{http://bird.kartaca.com/xmlschema/admin/delivery}AppMessageBody"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="link" type="{http://bird.kartaca.com/xmlschema/admin/common}AppMessageLinkType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppMessage", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", propOrder = {
    "body"
})
@XmlSeeAlso({
    PushMessageDto.class
})
public class AppMessageDto
    extends DeliveryItemDto
{

    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String body;
    @XmlAttribute(name = "link", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected AppMessageLinkType link;

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBody(String value) {
        this.body = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link AppMessageLinkType }
     *     
     */
    public AppMessageLinkType getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppMessageLinkType }
     *     
     */
    public void setLink(AppMessageLinkType value) {
        this.link = value;
    }

}
