//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppMessageLinkType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AppMessageLinkType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="WALL"/&gt;
 *     &lt;enumeration value="COIN_GAIN_VIDEO"/&gt;
 *     &lt;enumeration value="COIN_MAIN_PAGE"/&gt;
 *     &lt;enumeration value="COIN_HISTORY_PAGE_WEEKLY"/&gt;
 *     &lt;enumeration value="COIN_HISTORY_PAGE_MONTHLY"/&gt;
 *     &lt;enumeration value="COIN_HISTORY_PAGE_HALF_YEAR"/&gt;
 *     &lt;enumeration value="QRCODE_IDENTIFIER_PAGE"/&gt;
 *     &lt;enumeration value="LOYALTY_CARD_MAIN_PAGE"/&gt;
 *     &lt;enumeration value="LOYALTY_CARD_DETAIL_PAGE"/&gt;
 *     &lt;enumeration value="PROFILE_PAGE"/&gt;
 *     &lt;enumeration value="NOTIFICATIONS_PAGE"/&gt;
 *     &lt;enumeration value="ORDERS"/&gt;
 *     &lt;enumeration value="PROFILE_EDIT_PAGE"/&gt;
 *     &lt;enumeration value="SURVEY_PAGE"/&gt;
 *     &lt;enumeration value="SETTINGS_PAGE"/&gt;
 *     &lt;enumeration value="PERMISSIONS_PAGE"/&gt;
 *     &lt;enumeration value="ABOUT_PAGE"/&gt;
 *     &lt;enumeration value="AGREEMENT_PAGE"/&gt;
 *     &lt;enumeration value="PRIVACY_POLICY_PAGE"/&gt;
 *     &lt;enumeration value="HELP_PAGE"/&gt;
 *     &lt;enumeration value="BRANDS_PAGE"/&gt;
 *     &lt;enumeration value="CAMPAIGN_DETAIL_PAGE"/&gt;
 *     &lt;enumeration value="FAVORITES_PAGE"/&gt;
 *     &lt;enumeration value="CAMPAIGN_BANNER_DETAIL_PAGE"/&gt;
 *     &lt;enumeration value="POPUP_MESSAGE"/&gt;
 *     &lt;enumeration value="CLOSE"/&gt;
 *     &lt;enumeration value="CAMPAIGN_FILTER_DETAIL_PAGE"/&gt;
 *     &lt;enumeration value="INVITE_PAGE"/&gt;
 *     &lt;enumeration value="BRAND_DETAIL_PAGE"/&gt;
 *     &lt;enumeration value="NEARBY_STORES_PAGE"/&gt;
 *     &lt;enumeration value="STORE_MAP_PAGE"/&gt;
 *     &lt;enumeration value="SEARCH_PAGE"/&gt;
 *     &lt;enumeration value="PAYMENT_PAGE"/&gt;
 *     &lt;enumeration value="COIN_TRANSFER_GAIN_PAGE"/&gt;
 *     &lt;enumeration value="PROMOTION_CODE_PAGE"/&gt;
 *     &lt;enumeration value="CREDIT_CARD_MAIN_PAGE"/&gt;
 *     &lt;enumeration value="DOWNLOAD_STORE"/&gt;
 *     &lt;enumeration value="GIFT_COIN_GAIN"/&gt;
 *     &lt;enumeration value="PRODUCT_FAVORITES_PAGE"/&gt;
 *     &lt;enumeration value="PRODUCT_BARCODE_SEARCH_PAGE"/&gt;
 *     &lt;enumeration value="PRODUCT_IMAGE_SEARCH_PAGE"/&gt;
 *     &lt;enumeration value="PRODUCT_DETAIL_PAGE"/&gt;
 *     &lt;enumeration value="PRODUCT_SEARCH_PAGE"/&gt;
 *     &lt;enumeration value="CAMPAIGN_SEARCH_PAGE"/&gt;
 *     &lt;enumeration value="FUEL_COIN_PAGE"/&gt;
 *     &lt;whiteSpace value="collapse"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AppMessageLinkType", namespace = "http://bird.kartaca.com/xmlschema/admin/common")
@XmlEnum
public enum AppMessageLinkType {

    WALL,
    COIN_GAIN_VIDEO,
    COIN_MAIN_PAGE,
    COIN_HISTORY_PAGE_WEEKLY,
    COIN_HISTORY_PAGE_MONTHLY,
    COIN_HISTORY_PAGE_HALF_YEAR,
    QRCODE_IDENTIFIER_PAGE,
    LOYALTY_CARD_MAIN_PAGE,
    LOYALTY_CARD_DETAIL_PAGE,
    PROFILE_PAGE,
    NOTIFICATIONS_PAGE,
    ORDERS,
    PROFILE_EDIT_PAGE,
    SURVEY_PAGE,
    SETTINGS_PAGE,
    PERMISSIONS_PAGE,
    ABOUT_PAGE,
    AGREEMENT_PAGE,
    PRIVACY_POLICY_PAGE,
    HELP_PAGE,
    BRANDS_PAGE,
    CAMPAIGN_DETAIL_PAGE,
    FAVORITES_PAGE,
    CAMPAIGN_BANNER_DETAIL_PAGE,
    POPUP_MESSAGE,
    CLOSE,
    CAMPAIGN_FILTER_DETAIL_PAGE,
    INVITE_PAGE,
    BRAND_DETAIL_PAGE,
    NEARBY_STORES_PAGE,
    STORE_MAP_PAGE,
    SEARCH_PAGE,
    PAYMENT_PAGE,
    COIN_TRANSFER_GAIN_PAGE,
    PROMOTION_CODE_PAGE,
    CREDIT_CARD_MAIN_PAGE,
    DOWNLOAD_STORE,
    GIFT_COIN_GAIN,
    PRODUCT_FAVORITES_PAGE,
    PRODUCT_BARCODE_SEARCH_PAGE,
    PRODUCT_IMAGE_SEARCH_PAGE,
    PRODUCT_DETAIL_PAGE,
    PRODUCT_SEARCH_PAGE,
    CAMPAIGN_SEARCH_PAGE,
    FUEL_COIN_PAGE;

    public String value() {
        return name();
    }

    public static AppMessageLinkType fromValue(String v) {
        return valueOf(v);
    }

}
