//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Banner complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Banner"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://bird.kartaca.com/xmlschema/admin/delivery}DeliveryItem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bannerId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Banner", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", propOrder = {
    "bannerId"
})
public class BannerDto
    extends DeliveryItemDto
{

    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected long bannerId;

    /**
     * Gets the value of the bannerId property.
     * 
     */
    public long getBannerId() {
        return bannerId;
    }

    /**
     * Sets the value of the bannerId property.
     * 
     */
    public void setBannerId(long value) {
        this.bannerId = value;
    }

}
