//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChangeUserCoinTransferBlockStatusResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeUserCoinTransferBlockStatusResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="recipient" type="{http://bird.kartaca.com/xmlschema/admin/delivery}ChangeUserCoinTransferBlockRecipient"/&gt;
 *         &lt;element name="status" type="{http://bird.kartaca.com/xmlschema/admin/delivery}ChangeUserCoinTransferBlockStatusAnswer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeUserCoinTransferBlockStatusResponse", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", propOrder = {
    "recipient",
    "status"
})
public class ChangeUserCoinTransferBlockStatusResponseDto {

    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected ChangeUserCoinTransferBlockRecipientDto recipient;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    @XmlSchemaType(name = "string")
    protected ChangeUserCoinTransferBlockStatusAnswer status;

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeUserCoinTransferBlockRecipientDto }
     *     
     */
    public ChangeUserCoinTransferBlockRecipientDto getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeUserCoinTransferBlockRecipientDto }
     *     
     */
    public void setRecipient(ChangeUserCoinTransferBlockRecipientDto value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeUserCoinTransferBlockStatusAnswer }
     *     
     */
    public ChangeUserCoinTransferBlockStatusAnswer getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeUserCoinTransferBlockStatusAnswer }
     *     
     */
    public void setStatus(ChangeUserCoinTransferBlockStatusAnswer value) {
        this.status = value;
    }

}
