//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoinInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoinInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="amount" type="{http://bird.kartaca.com/xmlschema/admin/common}BigDecimal"/&gt;
 *         &lt;element name="coinVariant" type="{http://bird.kartaca.com/xmlschema/admin/common}CoinVariant" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoinInfo", namespace = "http://bird.kartaca.com/xmlschema/admin/common", propOrder = {
    "amount",
    "coinVariant"
})
public class CoinInfo {

    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/common", required = true)
    protected BigDecimal amount;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/common")
    @XmlSchemaType(name = "string")
    protected CoinVariant coinVariant;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the coinVariant property.
     * 
     * @return
     *     possible object is
     *     {@link CoinVariant }
     *     
     */
    public CoinVariant getCoinVariant() {
        return coinVariant;
    }

    /**
     * Sets the value of the coinVariant property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoinVariant }
     *     
     */
    public void setCoinVariant(CoinVariant value) {
        this.coinVariant = value;
    }

}
