//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryRecipientAnswer.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeliveryRecipientAnswer"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACCEPTED"/&gt;
 *     &lt;enumeration value="INVALID_MSISDN"/&gt;
 *     &lt;enumeration value="INVALID_USER_ID"/&gt;
 *     &lt;enumeration value="MALFORMED_PLACEHOLDER_CONTENT"/&gt;
 *     &lt;enumeration value="MALFORMED_VALUE"/&gt;
 *     &lt;enumeration value="PLACEHOLDER_VALUE_ERRROR"/&gt;
 *     &lt;enumeration value="PLACEHOLDER_CAMPAIGN_NOT_FOUND"/&gt;
 *     &lt;enumeration value="PLACEHOLDER_LOYALTY_CARD_NOT_FOUND"/&gt;
 *     &lt;enumeration value="PLACEHOLDER_CAMPAIGN_BANNER_NOT_FOUND"/&gt;
 *     &lt;enumeration value="PLACEHOLDER_CAMPAIGN_FILTER_NOT_FOUND"/&gt;
 *     &lt;enumeration value="PLACEHOLDER_MERCHANT_NOT_FOUND"/&gt;
 *     &lt;enumeration value="IN_APP_TEMPLATE_NOT_FOUND"/&gt;
 *     &lt;enumeration value="USER_NOT_FOUND"/&gt;
 *     &lt;enumeration value="USER_NOT_PERMITTED"/&gt;
 *     &lt;enumeration value="USER_HAS_NO_FAVORITES"/&gt;
 *     &lt;enumeration value="MISSING_LINKED_CAMPAIGN_ID"/&gt;
 *     &lt;enumeration value="MISSING_LINKED_LOYALTY_CARD_ID"/&gt;
 *     &lt;enumeration value="MISSING_LINKED_CAMPAIGN_BANNER_ID"/&gt;
 *     &lt;enumeration value="MISSING_LINKED_CAMPAIGN_FILTER_ID"/&gt;
 *     &lt;enumeration value="MISSING_LINKED_BRAND_ID"/&gt;
 *     &lt;enumeration value="MISSING_LINKED_STORE_ID"/&gt;
 *     &lt;enumeration value="MISSING_EARNED_COIN_AMOUNT"/&gt;
 *     &lt;enumeration value="MISSING_EARNED_COIN_MERCHANT_ID"/&gt;
 *     &lt;enumeration value="MISSING_IN_APP_TEMPLATE_ID"/&gt;
 *     &lt;enumeration value="MISSING_PRODUCT_ID"/&gt;
 *     &lt;enumeration value="MISSING_SEARCH_TEXT"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_NOT_ACTIVE"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_NOT_VISIBLE"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_NOT_FOUND"/&gt;
 *     &lt;enumeration value="EARNED_COIN_MERCHANT_NOT_FOUND"/&gt;
 *     &lt;enumeration value="LINKED_LOYALTY_CARD_NOT_FOUND"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_BANNER_NOT_FOUND"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_BANNER_NOT_ACTIVE"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_BANNER_HAS_NO_CAMPAIGNS"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_BANNER_HAS_NO_URL"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_BANNER_HAS_NO_LINKED_ID"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_BANNER_HAS_NO_LINK_TYPE"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_BANNER_NOT_ASSIGNED"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_FILTER_NOT_FOUND"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_FILTER_HAS_NO_CAMPAIGNS"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_NOT_ASSIGNED"/&gt;
 *     &lt;enumeration value="LINKED_LOYALTY_CARD_NOT_PAIRED"/&gt;
 *     &lt;enumeration value="LINKED_LOYALTY_CARD_MULTIPLE_PAIRED"/&gt;
 *     &lt;enumeration value="LINKED_BRAND_NOT_FOUND"/&gt;
 *     &lt;enumeration value="LINKED_BRAND_NOT_VISIBLE"/&gt;
 *     &lt;enumeration value="LINKED_BRAND_HAS_NO_CAMPAIGNS"/&gt;
 *     &lt;enumeration value="LINKED_STORE_NOT_FOUND"/&gt;
 *     &lt;enumeration value="MISSING_EMAIL_ADDRESS"/&gt;
 *     &lt;enumeration value="MISSING_DEVICE_PLATFORM"/&gt;
 *     &lt;enumeration value="MISSING_CLIENT_VERSION"/&gt;
 *     &lt;enumeration value="UNSUPPORTED_DEVICE_PLATFORM"/&gt;
 *     &lt;enumeration value="MISSING_NOTIFICATION_TOKEN"/&gt;
 *     &lt;enumeration value="DELIVERY_TYPE_NOT_IMPLEMENTED_YET"/&gt;
 *     &lt;enumeration value="RECIPIENT_TYPE_NOT_IMPLEMENTED_YET"/&gt;
 *     &lt;enumeration value="UNSUPPORTED_LINK_TYPE"/&gt;
 *     &lt;enumeration value="SENDING_CAMPAIGN_NOT_ACTIVE"/&gt;
 *     &lt;enumeration value="SENDING_CAMPAIGN_NOT_FOUND"/&gt;
 *     &lt;enumeration value="LINKED_CAMPAIGN_NOT_FOUND"/&gt;
 *     &lt;enumeration value="SENDING_CAMPAIGN_NOT_TARGETED"/&gt;
 *     &lt;enumeration value="SENDING_CAMPAIGN_ALREADY_SENT"/&gt;
 *     &lt;enumeration value="ONLINE_STORE_NOT_SUPPORTED"/&gt;
 *     &lt;enumeration value="MAX_ALLOWED_PRIORITY_REACHED"/&gt;
 *     &lt;enumeration value="OUT_OF_TIME_RANGE"/&gt;
 *     &lt;enumeration value="SENDING_BANNER_NOT_FOUND"/&gt;
 *     &lt;enumeration value="SENDING_BANNER_NOT_ACTIVE"/&gt;
 *     &lt;enumeration value="SENDING_BANNER_NOT_TARGETED"/&gt;
 *     &lt;enumeration value="SENDING_BANNER_ALREADY_SENT"/&gt;
 *     &lt;enumeration value="PRODUCT_NOT_FOUND"/&gt;
 *     &lt;enumeration value="UNEXPECTED_ERROR"/&gt;
 *     &lt;whiteSpace value="collapse"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DeliveryRecipientAnswer", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
@XmlEnum
public enum DeliveryRecipientAnswer {

    ACCEPTED,
    INVALID_MSISDN,
    INVALID_USER_ID,
    MALFORMED_PLACEHOLDER_CONTENT,
    MALFORMED_VALUE,
    PLACEHOLDER_VALUE_ERRROR,
    PLACEHOLDER_CAMPAIGN_NOT_FOUND,
    PLACEHOLDER_LOYALTY_CARD_NOT_FOUND,
    PLACEHOLDER_CAMPAIGN_BANNER_NOT_FOUND,
    PLACEHOLDER_CAMPAIGN_FILTER_NOT_FOUND,
    PLACEHOLDER_MERCHANT_NOT_FOUND,
    IN_APP_TEMPLATE_NOT_FOUND,
    USER_NOT_FOUND,
    USER_NOT_PERMITTED,
    USER_HAS_NO_FAVORITES,
    MISSING_LINKED_CAMPAIGN_ID,
    MISSING_LINKED_LOYALTY_CARD_ID,
    MISSING_LINKED_CAMPAIGN_BANNER_ID,
    MISSING_LINKED_CAMPAIGN_FILTER_ID,
    MISSING_LINKED_BRAND_ID,
    MISSING_LINKED_STORE_ID,
    MISSING_EARNED_COIN_AMOUNT,
    MISSING_EARNED_COIN_MERCHANT_ID,
    MISSING_IN_APP_TEMPLATE_ID,
    MISSING_PRODUCT_ID,
    MISSING_SEARCH_TEXT,
    LINKED_CAMPAIGN_NOT_ACTIVE,
    LINKED_CAMPAIGN_NOT_VISIBLE,
    LINKED_CAMPAIGN_NOT_FOUND,
    EARNED_COIN_MERCHANT_NOT_FOUND,
    LINKED_LOYALTY_CARD_NOT_FOUND,
    LINKED_CAMPAIGN_BANNER_NOT_FOUND,
    LINKED_CAMPAIGN_BANNER_NOT_ACTIVE,
    LINKED_CAMPAIGN_BANNER_HAS_NO_CAMPAIGNS,
    LINKED_CAMPAIGN_BANNER_HAS_NO_URL,
    LINKED_CAMPAIGN_BANNER_HAS_NO_LINKED_ID,
    LINKED_CAMPAIGN_BANNER_HAS_NO_LINK_TYPE,
    LINKED_CAMPAIGN_BANNER_NOT_ASSIGNED,
    LINKED_CAMPAIGN_FILTER_NOT_FOUND,
    LINKED_CAMPAIGN_FILTER_HAS_NO_CAMPAIGNS,
    LINKED_CAMPAIGN_NOT_ASSIGNED,
    LINKED_LOYALTY_CARD_NOT_PAIRED,
    LINKED_LOYALTY_CARD_MULTIPLE_PAIRED,
    LINKED_BRAND_NOT_FOUND,
    LINKED_BRAND_NOT_VISIBLE,
    LINKED_BRAND_HAS_NO_CAMPAIGNS,
    LINKED_STORE_NOT_FOUND,
    MISSING_EMAIL_ADDRESS,
    MISSING_DEVICE_PLATFORM,
    MISSING_CLIENT_VERSION,
    UNSUPPORTED_DEVICE_PLATFORM,
    MISSING_NOTIFICATION_TOKEN,
    DELIVERY_TYPE_NOT_IMPLEMENTED_YET,
    RECIPIENT_TYPE_NOT_IMPLEMENTED_YET,
    UNSUPPORTED_LINK_TYPE,
    SENDING_CAMPAIGN_NOT_ACTIVE,
    SENDING_CAMPAIGN_NOT_FOUND,
    SENDING_CAMPAIGN_NOT_TARGETED,
    SENDING_CAMPAIGN_ALREADY_SENT,
    ONLINE_STORE_NOT_SUPPORTED,
    MAX_ALLOWED_PRIORITY_REACHED,
    OUT_OF_TIME_RANGE,
    SENDING_BANNER_NOT_FOUND,
    SENDING_BANNER_NOT_ACTIVE,
    SENDING_BANNER_NOT_TARGETED,
    SENDING_BANNER_ALREADY_SENT,
    PRODUCT_NOT_FOUND,
    UNEXPECTED_ERROR;

    public String value() {
        return name();
    }

    public static DeliveryRecipientAnswer fromValue(String v) {
        return valueOf(v);
    }

}
