//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmailMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmailMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://bird.kartaca.com/xmlschema/admin/delivery}DeliveryItem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subject" type="{http://bird.kartaca.com/xmlschema/admin/delivery}EmailMessageSubject"/&gt;
 *         &lt;element name="body" type="{http://bird.kartaca.com/xmlschema/admin/delivery}EmailMessageBody"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmailMessage", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", propOrder = {
    "subject",
    "body"
})
public class EmailMessageDto
    extends DeliveryItemDto
{

    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String subject;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String body;

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBody(String value) {
        this.body = value;
    }

}
