//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="campaignId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *           &lt;element name="bannerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="linkType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ttl" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="linkId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="notificationSound" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fieldDelimiter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="recordDelimiter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isPermanent" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="richPush" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "campaignId",
    "bannerId",
    "fileName",
    "message",
    "linkType",
    "ttl",
    "linkId",
    "notificationSound",
    "fieldDelimiter",
    "recordDelimiter",
    "isPermanent",
    "priority",
    "richPush"
})
@XmlRootElement(name = "exportTargettedRecipentsRequest", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
public class ExportTargettedRecipentsRequest {

    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long campaignId;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long bannerId;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String fileName;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String message;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String linkType;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected long ttl;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String linkId;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String notificationSound;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String fieldDelimiter;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected String recordDelimiter;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected boolean isPermanent;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", defaultValue = "0")
    protected long priority;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", defaultValue = "false")
    protected Boolean richPush;

    /**
     * Gets the value of the campaignId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCampaignId() {
        return campaignId;
    }

    /**
     * Sets the value of the campaignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCampaignId(Long value) {
        this.campaignId = value;
    }

    /**
     * Gets the value of the bannerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBannerId() {
        return bannerId;
    }

    /**
     * Sets the value of the bannerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBannerId(Long value) {
        this.bannerId = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the linkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * Sets the value of the linkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkType(String value) {
        this.linkType = value;
    }

    /**
     * Gets the value of the ttl property.
     * 
     */
    public long getTtl() {
        return ttl;
    }

    /**
     * Sets the value of the ttl property.
     * 
     */
    public void setTtl(long value) {
        this.ttl = value;
    }

    /**
     * Gets the value of the linkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * Sets the value of the linkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkId(String value) {
        this.linkId = value;
    }

    /**
     * Gets the value of the notificationSound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationSound() {
        return notificationSound;
    }

    /**
     * Sets the value of the notificationSound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationSound(String value) {
        this.notificationSound = value;
    }

    /**
     * Gets the value of the fieldDelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldDelimiter() {
        return fieldDelimiter;
    }

    /**
     * Sets the value of the fieldDelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldDelimiter(String value) {
        this.fieldDelimiter = value;
    }

    /**
     * Gets the value of the recordDelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordDelimiter() {
        return recordDelimiter;
    }

    /**
     * Sets the value of the recordDelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordDelimiter(String value) {
        this.recordDelimiter = value;
    }

    /**
     * Gets the value of the isPermanent property.
     * 
     */
    public boolean isIsPermanent() {
        return isPermanent;
    }

    /**
     * Sets the value of the isPermanent property.
     * 
     */
    public void setIsPermanent(boolean value) {
        this.isPermanent = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public long getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(long value) {
        this.priority = value;
    }

    /**
     * Gets the value of the richPush property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRichPush() {
        return richPush;
    }

    /**
     * Sets the value of the richPush property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRichPush(Boolean value) {
        this.richPush = value;
    }

}
