//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb_version package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RecipientDtoPlaceholder_QNAME = new QName("http://bird.kartaca.com/xmlschema/admin/delivery", "placeholder");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb_version
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmptyContent }
     * 
     */
    public EmptyContent createEmptyContent() {
        return new EmptyContent();
    }

    /**
     * Create an instance of {@link StreamAndTitleViewItemDto }
     * 
     */
    public StreamAndTitleViewItemDto createStreamAndTitleViewItemDto() {
        return new StreamAndTitleViewItemDto();
    }

    /**
     * Create an instance of {@link ImageCollectionDto }
     * 
     */
    public ImageCollectionDto createImageCollectionDto() {
        return new ImageCollectionDto();
    }

    /**
     * Create an instance of {@link StringCollectionDto }
     * 
     */
    public StringCollectionDto createStringCollectionDto() {
        return new StringCollectionDto();
    }

    /**
     * Create an instance of {@link LongList }
     * 
     */
    public LongList createLongList() {
        return new LongList();
    }

    /**
     * Create an instance of {@link StreamAndTitleCollectionDto }
     * 
     */
    public StreamAndTitleCollectionDto createStreamAndTitleCollectionDto() {
        return new StreamAndTitleCollectionDto();
    }

    /**
     * Create an instance of {@link GeoLocationDto }
     * 
     */
    public GeoLocationDto createGeoLocationDto() {
        return new GeoLocationDto();
    }

    /**
     * Create an instance of {@link GenderDto }
     * 
     */
    public GenderDto createGenderDto() {
        return new GenderDto();
    }

    /**
     * Create an instance of {@link HtmlBasicPageViewItemDto }
     * 
     */
    public HtmlBasicPageViewItemDto createHtmlBasicPageViewItemDto() {
        return new HtmlBasicPageViewItemDto();
    }

    /**
     * Create an instance of {@link IntervalDto }
     * 
     */
    public IntervalDto createIntervalDto() {
        return new IntervalDto();
    }

    /**
     * Create an instance of {@link CityDto }
     * 
     */
    public CityDto createCityDto() {
        return new CityDto();
    }

    /**
     * Create an instance of {@link DistrictDto }
     * 
     */
    public DistrictDto createDistrictDto() {
        return new DistrictDto();
    }

    /**
     * Create an instance of {@link CoinInfo }
     * 
     */
    public CoinInfo createCoinInfo() {
        return new CoinInfo();
    }

    /**
     * Create an instance of {@link ValidStoreRestriction }
     * 
     */
    public ValidStoreRestriction createValidStoreRestriction() {
        return new ValidStoreRestriction();
    }

    /**
     * Create an instance of {@link SendMessageRequest }
     * 
     */
    public SendMessageRequest createSendMessageRequest() {
        return new SendMessageRequest();
    }

    /**
     * Create an instance of {@link RecipientDto }
     * 
     */
    public RecipientDto createRecipientDto() {
        return new RecipientDto();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link DeliveryResponseDto }
     * 
     */
    public DeliveryResponseDto createDeliveryResponseDto() {
        return new DeliveryResponseDto();
    }

    /**
     * Create an instance of {@link SendCampaignRequest }
     * 
     */
    public SendCampaignRequest createSendCampaignRequest() {
        return new SendCampaignRequest();
    }

    /**
     * Create an instance of {@link CampaignDto }
     * 
     */
    public CampaignDto createCampaignDto() {
        return new CampaignDto();
    }

    /**
     * Create an instance of {@link SendCampaignResponse }
     * 
     */
    public SendCampaignResponse createSendCampaignResponse() {
        return new SendCampaignResponse();
    }

    /**
     * Create an instance of {@link RemoveCampaignRequest }
     * 
     */
    public RemoveCampaignRequest createRemoveCampaignRequest() {
        return new RemoveCampaignRequest();
    }

    /**
     * Create an instance of {@link DeletedCampaignDto }
     * 
     */
    public DeletedCampaignDto createDeletedCampaignDto() {
        return new DeletedCampaignDto();
    }

    /**
     * Create an instance of {@link RemoveCampaignResponse }
     * 
     */
    public RemoveCampaignResponse createRemoveCampaignResponse() {
        return new RemoveCampaignResponse();
    }

    /**
     * Create an instance of {@link SendBannerRequest }
     * 
     */
    public SendBannerRequest createSendBannerRequest() {
        return new SendBannerRequest();
    }

    /**
     * Create an instance of {@link BannerDto }
     * 
     */
    public BannerDto createBannerDto() {
        return new BannerDto();
    }

    /**
     * Create an instance of {@link SendBannerResponse }
     * 
     */
    public SendBannerResponse createSendBannerResponse() {
        return new SendBannerResponse();
    }

    /**
     * Create an instance of {@link ExportTargettedRecipentsRequest }
     * 
     */
    public ExportTargettedRecipentsRequest createExportTargettedRecipentsRequest() {
        return new ExportTargettedRecipentsRequest();
    }

    /**
     * Create an instance of {@link AssignCoinGameRequest }
     * 
     */
    public AssignCoinGameRequest createAssignCoinGameRequest() {
        return new AssignCoinGameRequest();
    }

    /**
     * Create an instance of {@link CoinGameRecipientDto }
     * 
     */
    public CoinGameRecipientDto createCoinGameRecipientDto() {
        return new CoinGameRecipientDto();
    }

    /**
     * Create an instance of {@link AssignCoinGameResponse }
     * 
     */
    public AssignCoinGameResponse createAssignCoinGameResponse() {
        return new AssignCoinGameResponse();
    }

    /**
     * Create an instance of {@link AssignCoinGameResponseDto }
     * 
     */
    public AssignCoinGameResponseDto createAssignCoinGameResponseDto() {
        return new AssignCoinGameResponseDto();
    }

    /**
     * Create an instance of {@link PickEligibleCampaignRequest }
     * 
     */
    public PickEligibleCampaignRequest createPickEligibleCampaignRequest() {
        return new PickEligibleCampaignRequest();
    }

    /**
     * Create an instance of {@link PickEligibleCampaignResponse }
     * 
     */
    public PickEligibleCampaignResponse createPickEligibleCampaignResponse() {
        return new PickEligibleCampaignResponse();
    }

    /**
     * Create an instance of {@link GetEmailUnsubscribeLinkRequest }
     * 
     */
    public GetEmailUnsubscribeLinkRequest createGetEmailUnsubscribeLinkRequest() {
        return new GetEmailUnsubscribeLinkRequest();
    }

    /**
     * Create an instance of {@link EmailUnsubscribeLinkRecipientDto }
     * 
     */
    public EmailUnsubscribeLinkRecipientDto createEmailUnsubscribeLinkRecipientDto() {
        return new EmailUnsubscribeLinkRecipientDto();
    }

    /**
     * Create an instance of {@link GetEmailUnsubscribeLinkResponse }
     * 
     */
    public GetEmailUnsubscribeLinkResponse createGetEmailUnsubscribeLinkResponse() {
        return new GetEmailUnsubscribeLinkResponse();
    }

    /**
     * Create an instance of {@link ChangeUserCoinTransferBlockStatusRequest }
     * 
     */
    public ChangeUserCoinTransferBlockStatusRequest createChangeUserCoinTransferBlockStatusRequest() {
        return new ChangeUserCoinTransferBlockStatusRequest();
    }

    /**
     * Create an instance of {@link ChangeUserCoinTransferBlockRecipientDto }
     * 
     */
    public ChangeUserCoinTransferBlockRecipientDto createChangeUserCoinTransferBlockRecipientDto() {
        return new ChangeUserCoinTransferBlockRecipientDto();
    }

    /**
     * Create an instance of {@link ChangeUserCoinTransferBlockStatusResponse }
     * 
     */
    public ChangeUserCoinTransferBlockStatusResponse createChangeUserCoinTransferBlockStatusResponse() {
        return new ChangeUserCoinTransferBlockStatusResponse();
    }

    /**
     * Create an instance of {@link ChangeUserCoinTransferBlockStatusResponseDto }
     * 
     */
    public ChangeUserCoinTransferBlockStatusResponseDto createChangeUserCoinTransferBlockStatusResponseDto() {
        return new ChangeUserCoinTransferBlockStatusResponseDto();
    }

    /**
     * Create an instance of {@link SetUserStatusAndHistoryRequest }
     * 
     */
    public SetUserStatusAndHistoryRequest createSetUserStatusAndHistoryRequest() {
        return new SetUserStatusAndHistoryRequest();
    }

    /**
     * Create an instance of {@link UserStatusHistoryRecipientDto }
     * 
     */
    public UserStatusHistoryRecipientDto createUserStatusHistoryRecipientDto() {
        return new UserStatusHistoryRecipientDto();
    }

    /**
     * Create an instance of {@link UserStatusHistoryDto }
     * 
     */
    public UserStatusHistoryDto createUserStatusHistoryDto() {
        return new UserStatusHistoryDto();
    }

    /**
     * Create an instance of {@link SetUserStatusAndHistoryResponse }
     * 
     */
    public SetUserStatusAndHistoryResponse createSetUserStatusAndHistoryResponse() {
        return new SetUserStatusAndHistoryResponse();
    }

    /**
     * Create an instance of {@link PlaceholderDto }
     * 
     */
    public PlaceholderDto createPlaceholderDto() {
        return new PlaceholderDto();
    }

    /**
     * Create an instance of {@link AppMessageDto }
     * 
     */
    public AppMessageDto createAppMessageDto() {
        return new AppMessageDto();
    }

    /**
     * Create an instance of {@link PushMessageDto }
     * 
     */
    public PushMessageDto createPushMessageDto() {
        return new PushMessageDto();
    }

    /**
     * Create an instance of {@link SmsMessageDto }
     * 
     */
    public SmsMessageDto createSmsMessageDto() {
        return new SmsMessageDto();
    }

    /**
     * Create an instance of {@link EmailMessageDto }
     * 
     */
    public EmailMessageDto createEmailMessageDto() {
        return new EmailMessageDto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceholderDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", name = "placeholder", scope = RecipientDto.class)
    public JAXBElement<PlaceholderDto> createRecipientDtoPlaceholder(PlaceholderDto value) {
        return new JAXBElement<PlaceholderDto>(_RecipientDtoPlaceholder_QNAME, PlaceholderDto.class, RecipientDto.class, value);
    }

}
