//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PushMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PushMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://bird.kartaca.com/xmlschema/admin/delivery}AppMessage"&gt;
 *       &lt;attribute name="checkPermission" type="{http://bird.kartaca.com/xmlschema/admin/delivery}PushNotificationPermissionType" default="CAMPAIGN_NOTIFICATION" /&gt;
 *       &lt;attribute name="batchId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}BatchId" /&gt;
 *       &lt;attribute name="richPush" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PushMessage", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
public class PushMessageDto
    extends AppMessageDto
{

    @XmlAttribute(name = "checkPermission", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected PushNotificationPermissionType checkPermission;
    @XmlAttribute(name = "batchId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String batchId;
    @XmlAttribute(name = "richPush", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Boolean richPush;

    /**
     * Gets the value of the checkPermission property.
     * 
     * @return
     *     possible object is
     *     {@link PushNotificationPermissionType }
     *     
     */
    public PushNotificationPermissionType getCheckPermission() {
        if (checkPermission == null) {
            return PushNotificationPermissionType.CAMPAIGN_NOTIFICATION;
        } else {
            return checkPermission;
        }
    }

    /**
     * Sets the value of the checkPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link PushNotificationPermissionType }
     *     
     */
    public void setCheckPermission(PushNotificationPermissionType value) {
        this.checkPermission = value;
    }

    /**
     * Gets the value of the batchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * Sets the value of the batchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchId(String value) {
        this.batchId = value;
    }

    /**
     * Gets the value of the richPush property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRichPush() {
        if (richPush == null) {
            return false;
        } else {
            return richPush;
        }
    }

    /**
     * Sets the value of the richPush property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRichPush(Boolean value) {
        this.richPush = value;
    }

}
