//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Recipient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Recipient"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="placeholder" type="{http://bird.kartaca.com/xmlschema/admin/delivery}Placeholder" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" type="{http://bird.kartaca.com/xmlschema/admin/delivery}RecipientType" default="USER_ID" /&gt;
 *       &lt;attribute name="transactionId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier" /&gt;
 *       &lt;attribute name="linkedCampaignId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier" /&gt;
 *       &lt;attribute name="linkedTemplateId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier" /&gt;
 *       &lt;attribute name="linkedLoyaltyCardId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier" /&gt;
 *       &lt;attribute name="linkedCampaignBannerId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier" /&gt;
 *       &lt;attribute name="linkedCampaignFilterId" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="linkedBrandId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier" /&gt;
 *       &lt;attribute name="linkedStoreId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier" /&gt;
 *       &lt;attribute name="earnedCoinAmount" type="{http://bird.kartaca.com/xmlschema/admin/delivery}EarnedCoinAmount" /&gt;
 *       &lt;attribute name="earnedCoinMerchantId" type="{http://bird.kartaca.com/xmlschema/admin/delivery}IntegerIdentifier" /&gt;
 *       &lt;attribute name="earnedCoinCause" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="earnedCoinAction" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="paymentAmount" type="{http://bird.kartaca.com/xmlschema/admin/delivery}PaymentAmount" /&gt;
 *       &lt;attribute name="gift" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="markAsRead" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="readDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="sentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="ttl" type="{http://bird.kartaca.com/xmlschema/admin/delivery}Ttl" default="7776000" /&gt;
 *       &lt;attribute name="displayOnStart" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="sound" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="link" type="{http://bird.kartaca.com/xmlschema/admin/common}AppMessageLinkType" /&gt;
 *       &lt;attribute name="messagePathId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="searchText" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="productId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="deliveryPriority" type="{http://bird.kartaca.com/xmlschema/admin/delivery}DeliveryPriority" default="1" /&gt;
 *       &lt;attribute name="expireMessage" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Recipient", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", propOrder = {
    "content"
})
public class RecipientDto {

    @XmlElementRef(name = "placeholder", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", type = JAXBElement.class, required = false)
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "type", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected RecipientType type;
    @XmlAttribute(name = "transactionId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long transactionId;
    @XmlAttribute(name = "linkedCampaignId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long linkedCampaignId;
    @XmlAttribute(name = "linkedTemplateId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long linkedTemplateId;
    @XmlAttribute(name = "linkedLoyaltyCardId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long linkedLoyaltyCardId;
    @XmlAttribute(name = "linkedCampaignBannerId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long linkedCampaignBannerId;
    @XmlAttribute(name = "linkedCampaignFilterId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long linkedCampaignFilterId;
    @XmlAttribute(name = "linkedBrandId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long linkedBrandId;
    @XmlAttribute(name = "linkedStoreId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long linkedStoreId;
    @XmlAttribute(name = "earnedCoinAmount", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected BigDecimal earnedCoinAmount;
    @XmlAttribute(name = "earnedCoinMerchantId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Long earnedCoinMerchantId;
    @XmlAttribute(name = "earnedCoinCause", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String earnedCoinCause;
    @XmlAttribute(name = "earnedCoinAction", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String earnedCoinAction;
    @XmlAttribute(name = "paymentAmount", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected BigDecimal paymentAmount;
    @XmlAttribute(name = "gift", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Boolean gift;
    @XmlAttribute(name = "markAsRead", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Boolean markAsRead;
    @XmlAttribute(name = "readDate", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar readDate;
    @XmlAttribute(name = "sentDate", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sentDate;
    @XmlAttribute(name = "ttl", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Integer ttl;
    @XmlAttribute(name = "displayOnStart", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Boolean displayOnStart;
    @XmlAttribute(name = "sound", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String sound;
    @XmlAttribute(name = "link", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected AppMessageLinkType link;
    @XmlAttribute(name = "messagePathId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String messagePathId;
    @XmlAttribute(name = "searchText", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String searchText;
    @XmlAttribute(name = "productId", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String productId;
    @XmlAttribute(name = "deliveryPriority", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected Integer deliveryPriority;
    @XmlAttribute(name = "expireMessage", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
    protected String expireMessage;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link JAXBElement }{@code <}{@link PlaceholderDto }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RecipientType }
     *     
     */
    public RecipientType getType() {
        if (type == null) {
            return RecipientType.USER_ID;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipientType }
     *     
     */
    public void setType(RecipientType value) {
        this.type = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTransactionId(Long value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the linkedCampaignId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkedCampaignId() {
        return linkedCampaignId;
    }

    /**
     * Sets the value of the linkedCampaignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkedCampaignId(Long value) {
        this.linkedCampaignId = value;
    }

    /**
     * Gets the value of the linkedTemplateId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkedTemplateId() {
        return linkedTemplateId;
    }

    /**
     * Sets the value of the linkedTemplateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkedTemplateId(Long value) {
        this.linkedTemplateId = value;
    }

    /**
     * Gets the value of the linkedLoyaltyCardId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkedLoyaltyCardId() {
        return linkedLoyaltyCardId;
    }

    /**
     * Sets the value of the linkedLoyaltyCardId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkedLoyaltyCardId(Long value) {
        this.linkedLoyaltyCardId = value;
    }

    /**
     * Gets the value of the linkedCampaignBannerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkedCampaignBannerId() {
        return linkedCampaignBannerId;
    }

    /**
     * Sets the value of the linkedCampaignBannerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkedCampaignBannerId(Long value) {
        this.linkedCampaignBannerId = value;
    }

    /**
     * Gets the value of the linkedCampaignFilterId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkedCampaignFilterId() {
        return linkedCampaignFilterId;
    }

    /**
     * Sets the value of the linkedCampaignFilterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkedCampaignFilterId(Long value) {
        this.linkedCampaignFilterId = value;
    }

    /**
     * Gets the value of the linkedBrandId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkedBrandId() {
        return linkedBrandId;
    }

    /**
     * Sets the value of the linkedBrandId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkedBrandId(Long value) {
        this.linkedBrandId = value;
    }

    /**
     * Gets the value of the linkedStoreId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkedStoreId() {
        return linkedStoreId;
    }

    /**
     * Sets the value of the linkedStoreId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkedStoreId(Long value) {
        this.linkedStoreId = value;
    }

    /**
     * Gets the value of the earnedCoinAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEarnedCoinAmount() {
        return earnedCoinAmount;
    }

    /**
     * Sets the value of the earnedCoinAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEarnedCoinAmount(BigDecimal value) {
        this.earnedCoinAmount = value;
    }

    /**
     * Gets the value of the earnedCoinMerchantId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEarnedCoinMerchantId() {
        return earnedCoinMerchantId;
    }

    /**
     * Sets the value of the earnedCoinMerchantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEarnedCoinMerchantId(Long value) {
        this.earnedCoinMerchantId = value;
    }

    /**
     * Gets the value of the earnedCoinCause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarnedCoinCause() {
        return earnedCoinCause;
    }

    /**
     * Sets the value of the earnedCoinCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarnedCoinCause(String value) {
        this.earnedCoinCause = value;
    }

    /**
     * Gets the value of the earnedCoinAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarnedCoinAction() {
        return earnedCoinAction;
    }

    /**
     * Sets the value of the earnedCoinAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarnedCoinAction(String value) {
        this.earnedCoinAction = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentAmount(BigDecimal value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the gift property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGift() {
        if (gift == null) {
            return false;
        } else {
            return gift;
        }
    }

    /**
     * Sets the value of the gift property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGift(Boolean value) {
        this.gift = value;
    }

    /**
     * Gets the value of the markAsRead property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMarkAsRead() {
        if (markAsRead == null) {
            return false;
        } else {
            return markAsRead;
        }
    }

    /**
     * Sets the value of the markAsRead property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarkAsRead(Boolean value) {
        this.markAsRead = value;
    }

    /**
     * Gets the value of the readDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReadDate() {
        return readDate;
    }

    /**
     * Sets the value of the readDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReadDate(XMLGregorianCalendar value) {
        this.readDate = value;
    }

    /**
     * Gets the value of the sentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSentDate() {
        return sentDate;
    }

    /**
     * Sets the value of the sentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSentDate(XMLGregorianCalendar value) {
        this.sentDate = value;
    }

    /**
     * Gets the value of the ttl property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTtl() {
        if (ttl == null) {
            return  7776000;
        } else {
            return ttl;
        }
    }

    /**
     * Sets the value of the ttl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTtl(Integer value) {
        this.ttl = value;
    }

    /**
     * Gets the value of the displayOnStart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDisplayOnStart() {
        if (displayOnStart == null) {
            return false;
        } else {
            return displayOnStart;
        }
    }

    /**
     * Sets the value of the displayOnStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayOnStart(Boolean value) {
        this.displayOnStart = value;
    }

    /**
     * Gets the value of the sound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSound() {
        return sound;
    }

    /**
     * Sets the value of the sound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSound(String value) {
        this.sound = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link AppMessageLinkType }
     *     
     */
    public AppMessageLinkType getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppMessageLinkType }
     *     
     */
    public void setLink(AppMessageLinkType value) {
        this.link = value;
    }

    /**
     * Gets the value of the messagePathId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessagePathId() {
        return messagePathId;
    }

    /**
     * Sets the value of the messagePathId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessagePathId(String value) {
        this.messagePathId = value;
    }

    /**
     * Gets the value of the searchText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchText() {
        return searchText;
    }

    /**
     * Sets the value of the searchText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchText(String value) {
        this.searchText = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the deliveryPriority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDeliveryPriority() {
        if (deliveryPriority == null) {
            return  1;
        } else {
            return deliveryPriority;
        }
    }

    /**
     * Sets the value of the deliveryPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeliveryPriority(Integer value) {
        this.deliveryPriority = value;
    }

    /**
     * Gets the value of the expireMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireMessage() {
        return expireMessage;
    }

    /**
     * Sets the value of the expireMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireMessage(String value) {
        this.expireMessage = value;
    }

}
