//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="recipient" type="{http://bird.kartaca.com/xmlschema/admin/delivery}UserStatusHistoryRecipient"/&gt;
 *         &lt;element name="userStatusHistory" type="{http://bird.kartaca.com/xmlschema/admin/delivery}UserStatusHistory"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recipient",
    "userStatusHistory"
})
@XmlRootElement(name = "setUserStatusAndHistoryRequest", namespace = "http://bird.kartaca.com/xmlschema/admin/delivery")
public class SetUserStatusAndHistoryRequest {

    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected UserStatusHistoryRecipientDto recipient;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/delivery", required = true)
    protected UserStatusHistoryDto userStatusHistory;

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link UserStatusHistoryRecipientDto }
     *     
     */
    public UserStatusHistoryRecipientDto getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserStatusHistoryRecipientDto }
     *     
     */
    public void setRecipient(UserStatusHistoryRecipientDto value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the userStatusHistory property.
     * 
     * @return
     *     possible object is
     *     {@link UserStatusHistoryDto }
     *     
     */
    public UserStatusHistoryDto getUserStatusHistory() {
        return userStatusHistory;
    }

    /**
     * Sets the value of the userStatusHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserStatusHistoryDto }
     *     
     */
    public void setUserStatusHistory(UserStatusHistoryDto value) {
        this.userStatusHistory = value;
    }

}
