//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserStatusReasonEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UserStatusReasonEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACTIVE"/&gt;
 *     &lt;enumeration value="COMPLAINT"/&gt;
 *     &lt;enumeration value="FRAUD"/&gt;
 *     &lt;enumeration value="PAYMENT"/&gt;
 *     &lt;enumeration value="SUSPICIOUS"/&gt;
 *     &lt;enumeration value="USER_PREFERENCE"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UserStatusReasonEnum", namespace = "http://bird.kartaca.com/xmlschema/admin/common")
@XmlEnum
public enum UserStatusReasonEnum {

    ACTIVE,
    COMPLAINT,
    FRAUD,
    PAYMENT,
    SUSPICIOUS,
    USER_PREFERENCE,
    OTHER;

    public String value() {
        return name();
    }

    public static UserStatusReasonEnum fromValue(String v) {
        return valueOf(v);
    }

}
