//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for validStoreRestriction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="validStoreRestriction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="merchantId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="restrictionType" type="{http://bird.kartaca.com/xmlschema/admin/common}validStoreRestrictionType"/&gt;
 *         &lt;element name="specificStores" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="visibleInCoins" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="visibleInBrands" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="campaignOwner" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validStoreRestriction", namespace = "http://bird.kartaca.com/xmlschema/admin/common", propOrder = {
    "merchantId",
    "restrictionType",
    "specificStores",
    "visibleInCoins",
    "visibleInBrands",
    "campaignOwner"
})
public class ValidStoreRestriction {

    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/common")
    protected long merchantId;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/common", required = true)
    @XmlSchemaType(name = "string")
    protected ValidStoreRestrictionType restrictionType;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/common", type = Long.class)
    protected List<Long> specificStores;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/common", defaultValue = "true")
    protected Boolean visibleInCoins;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/common", defaultValue = "true")
    protected Boolean visibleInBrands;
    @XmlElement(namespace = "http://bird.kartaca.com/xmlschema/admin/common", defaultValue = "false")
    protected boolean campaignOwner;

    /**
     * Gets the value of the merchantId property.
     * 
     */
    public long getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the value of the merchantId property.
     * 
     */
    public void setMerchantId(long value) {
        this.merchantId = value;
    }

    /**
     * Gets the value of the restrictionType property.
     * 
     * @return
     *     possible object is
     *     {@link ValidStoreRestrictionType }
     *     
     */
    public ValidStoreRestrictionType getRestrictionType() {
        return restrictionType;
    }

    /**
     * Sets the value of the restrictionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidStoreRestrictionType }
     *     
     */
    public void setRestrictionType(ValidStoreRestrictionType value) {
        this.restrictionType = value;
    }

    /**
     * Gets the value of the specificStores property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specificStores property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecificStores().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getSpecificStores() {
        if (specificStores == null) {
            specificStores = new ArrayList<Long>();
        }
        return this.specificStores;
    }

    /**
     * Gets the value of the visibleInCoins property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisibleInCoins() {
        return visibleInCoins;
    }

    /**
     * Sets the value of the visibleInCoins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisibleInCoins(Boolean value) {
        this.visibleInCoins = value;
    }

    /**
     * Gets the value of the visibleInBrands property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisibleInBrands() {
        return visibleInBrands;
    }

    /**
     * Sets the value of the visibleInBrands property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisibleInBrands(Boolean value) {
        this.visibleInBrands = value;
    }

    /**
     * Gets the value of the campaignOwner property.
     * 
     */
    public boolean isCampaignOwner() {
        return campaignOwner;
    }

    /**
     * Sets the value of the campaignOwner property.
     * 
     */
    public void setCampaignOwner(boolean value) {
        this.campaignOwner = value;
    }

}
