//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 10:09:09 PM CET 
//


package jaxb_version;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for validStoreRestrictionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="validStoreRestrictionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ALL_STORES"/&gt;
 *     &lt;enumeration value="ONLINE_STORES"/&gt;
 *     &lt;enumeration value="OFFLINE_STORES"/&gt;
 *     &lt;enumeration value="SPECIFIC_STORES"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "validStoreRestrictionType", namespace = "http://bird.kartaca.com/xmlschema/admin/common")
@XmlEnum
public enum ValidStoreRestrictionType {

    ALL_STORES,
    ONLINE_STORES,
    OFFLINE_STORES,
    SPECIFIC_STORES;

    public String value() {
        return name();
    }

    public static ValidStoreRestrictionType fromValue(String v) {
        return valueOf(v);
    }

}
